version: ‘3’
services:
 postgres-primary:
   build: ./postgres-primary
   environment:
     - DB_REP_USER=postgres
     - DB_REP_PASS=1234567890
 pgpool:
   build: ./pgpool
   links:
     - postgres-primary
     - postgres-replica
   volumes:
     - ./pgpool/pgpool.conf:/etc/pgpool2/pgpool.conf
 postgres-replica:
    build: ./postgres-replica
    environment:
      - PRIMARY_DB_HOST=postgres-primary
      - PRIMARY_DB_PORT=5432
      - PRIMARY_DB_REP_USER=postgres
      - PRIMARY_DB_REP_PASS=1234567890
